---

mapping:
  12:
    - AS: 14
      IP: 10.1.12.2
    - AS: 15
      IP: 10.1.15.1
  13:
    - AS: 16
      IP: 10.1.13.2
    - AS: 17
      IP: 10.1.17.1
  14:
    - AS: 12
      IP: 10.1.12.1
    - AS: 18
      IP: 10.1.14.2
  15:
    - AS: 12
      IP: 10.1.15.2
    - AS: 16
      IP: 10.1.11.1
    - AS: 18
      IP: 10.1.18.1
    - AS: 19
      IP: 10.1.10.2
  16:
    - AS: 13
      IP: 10.1.13.1
    - AS: 15
      IP: 10.1.11.2
    - AS: 19
      IP: 10.1.9.1
    - AS: 20
      IP: 10.1.16.2
  17:
    - AS: 13
      IP: 10.1.17.2
    - AS: 20
      IP: 10.1.20.1
    - AS: 23
      IP: 10.1.23.1
  18:
    - AS: 14
      IP: 10.1.14.1
    - AS: 15
      IP: 10.1.18.2
    - AS: 19
      IP: 10.1.19.1
    - AS: 21
      IP: 10.1.21.1
  19:
    - AS: 15
      IP: 10.1.10.1
    - AS: 16
      IP: 10.1.9.2
    - AS: 18
      IP: 10.1.19.2
    - AS: 20
      IP: 10.1.25.2
    - AS: 22
      IP: 10.1.8.1
  20:
    - AS: 16
      IP: 10.1.16.1
    - AS: 17
      IP: 10.1.20.2
    - AS: 19
      IP: 10.1.25.1
  21:
    - AS: 18
      IP: 10.1.21.2
    - AS: 22
      IP: 10.1.22.1
  22:
    - AS: 19
      IP: 10.1.8.2
    - AS: 21
      IP: 10.1.22.2
    - AS: 23
      IP: 10.1.24.2
  23:
    - AS: 17
      IP: 10.1.23.2
    - AS: 22
      IP: 10.1.24.1

peerips:
  12: [10.1.12.1, 10.1.15.2]
  13: [10.1.13.1, 10.1.17.2]
  14: [10.1.12.2, 10.1.14.1]
  15: [10.1.10.1, 10.1.11.2, 10.1.15.1, 10.1.18.2]
  16: [10.1.9.2, 10.1.11.1, 10.1.13.2, 10.1.16.1]
  17: [10.1.17.1, 10.1.20.2, 10.1.23.2]
  18: [10.1.14.2, 10.1.18.1, 10.1.19.2, 10.1.21.2]
  19: [10.1.8.2, 10.1.9.1, 10.1.10.2, 10.1.19.1, 10.1.25.1]
  20: [10.1.16.2, 10.1.20.1, 10.1.25.2]
  21: [10.1.21.1, 10.1.22.2]
  22: [10.1.8.1, 10.1.22.1, 10.1.24.1]
  23: [10.1.23.1, 10.1.24.2]